"""Turn evaluation results into results/results.md and result figures."""
import matplotlib.pyplot as plt
import numpy as np

from src.config import CLASSES, FIGURES_DIR, ROOT
from src.explore import BLUE, GRID, INK, INK_2, ORANGE, style_grid  # also applies chart style

RUN_NAMES = {"cnn_hard": "CNN · hard", "cnn_soft": "CNN · soft",
             "resnet18_hard": "ResNet18 · hard", "resnet18_soft": "ResNet18 · soft"}
ARCHS = {"cnn": "Scratch CNN", "resnet18": "ResNet18 (ImageNet)"}
LABEL_COLOR = {"hard": BLUE, "soft": ORANGE, "human": "#a3a29b"}
LABEL_NAME = {"hard": "Hard (majority vote)", "soft": "Soft (vote share)",
              "human": "Humans (share agreeing with top vote)"}
SUBSET_NAMES = {"full": "Full test set", "dedup": "Test set without train duplicates"}


# ---------- markdown ----------

def fmt(x, pct=False):
    return f"{x:.1%}" if pct else f"{x:.3f}"


def write_markdown(results):
    M = results["metrics"]
    L = ["# Results", "",
         "Test set = FER+ PrivateTest. Generated by `python -m src.evaluate`.",
         f"\"Without duplicates\" removes the {results['n_duplicates_removed']} test images that have a "
         "pixel-identical copy in the training set.", "",
         "**Metrics:** *Acc (majority)* = prediction equals the majority label (ties broken at random).",
         "*Acc (any top vote)* = prediction is one of the most-voted emotions (fair on ties).",
         "*KL* = distance from the human vote distribution (lower is better).",
         "*ECE* = calibration error (lower is better). *Confidence* = average top predicted probability.", ""]

    for s in ["full", "dedup"]:
        L += [f"## {SUBSET_NAMES[s]} (n = {M[s]['cnn_hard']['n']})", "",
              "| model | Acc (majority) | Acc (any top vote) | Macro F1 | KL ↓ | ECE ↓ | Confidence |",
              "|---|---:|---:|---:|---:|---:|---:|"]
        for run, r in M[s].items():
            L.append(f"| {RUN_NAMES[run]} | {fmt(r['acc_majority'], 1)} | {fmt(r['acc_any_top'], 1)} | "
                     f"{fmt(r['macro_f1'])} | {fmt(r['kl'])} | {fmt(r['ece'])} | {fmt(r['mean_confidence'], 1)} |")
        L.append("")

    L += ["## Is the soft − hard difference real?", "",
          "95% paired bootstrap intervals over test images (2,000 resamples). An interval that excludes 0",
          "means the difference isn't explained by which test images we happened to have. "
          "Each model was trained once (one seed), so these intervals don't capture training randomness.", "",
          "| test set | model | Δ Acc (any top) | Δ Macro F1 | Δ KL |", "|---|---|---|---|---|"]
    for s in ["full", "dedup"]:
        for arch, ci in results["bootstrap_soft_minus_hard"][s].items():
            d = {k: M[s][f"{arch}_soft"][k] - M[s][f"{arch}_hard"][k] for k in ["acc_any_top", "macro_f1", "kl"]}
            L.append(f"| {s} | {ARCHS[arch]} | {d['acc_any_top']:+.1%} [{ci['acc_any_top'][0]:+.1%}, "
                     f"{ci['acc_any_top'][1]:+.1%}] | {d['macro_f1']:+.3f} [{ci['macro_f1'][0]:+.3f}, "
                     f"{ci['macro_f1'][1]:+.3f}] | {d['kl']:+.3f} [{ci['kl'][0]:+.3f}, {ci['kl'][1]:+.3f}] |")
    L.append("")

    for s in ["full", "dedup"]:
        buckets = list(M[s]["cnn_hard"]["by_ambiguity"])
        L += [f"## By ambiguity — {SUBSET_NAMES[s].lower()}", "",
              "Accuracy (any top vote) / KL / average confidence. *Human* = average share of annotators "
              "who chose the top emotion.", "",
              "| bucket | n | human | " + " | ".join(RUN_NAMES[r] for r in M[s]) + " |",
              "|---|---:|---:|" + "---|" * len(M[s])]
        for b in buckets:
            first = M[s]["cnn_hard"]["by_ambiguity"][b]
            cells = [f"{fmt(x['acc_any_top'], 1)} / {x['kl']:.2f} / {x['model_confidence']:.0%}"
                     for x in (M[s][run]["by_ambiguity"][b] for run in M[s])]
            L.append(f"| {b} | {first['n']} | {first['human_top_share']:.0%} | " + " | ".join(cells) + " |")
        L.append("")

    for s in ["full", "dedup"]:
        L += [f"## Per-class F1 — {SUBSET_NAMES[s].lower()}", "",
              "| class | " + " | ".join(RUN_NAMES[r] for r in M[s]) + " |", "|---|" + "---:|" * len(M[s])]
        for c in CLASSES:
            L.append(f"| {c} | " + " | ".join(f"{M[s][run]['per_class_f1'][c]:.3f}" for run in M[s]) + " |")
        L.append("")

    conf = results["confusion_full"]
    k = CLASSES.index("contempt")
    n_contempt = sum(conf["cnn_hard"][k])
    L += ["## Contempt", "",
          f"Only {n_contempt} test images have contempt as the majority label (full test set).", "",
          "| model | contempt F1 | correctly predicted | times the model predicted contempt |", "|---|---:|---:|---:|"]
    for run in conf:
        cm = np.array(conf[run])
        L.append(f"| {RUN_NAMES[run]} | {M['full'][run]['per_class_f1']['contempt']:.3f} | "
                 f"{cm[k, k]} / {n_contempt} | {cm[:, k].sum()} |")
    L.append("")
    (ROOT / "results" / "results.md").write_text("\n".join(L))


# ---------- figures ----------

def grouped_bars(ax, groups, values_by_label, fmt_str=None):
    """Side-by-side bars per group; values_by_label maps 'hard'/'soft'/'human' -> values."""
    labels = list(values_by_label)
    width = 0.8 / len(labels)
    x = np.arange(len(groups))
    for j, lab in enumerate(labels):
        vals = values_by_label[lab]
        offset = (j - (len(labels) - 1) / 2) * width
        bars = ax.bar(x + offset, vals, width=width * 0.94, color=LABEL_COLOR[lab], label=LABEL_NAME[lab])
        if fmt_str:
            for bar, v in zip(bars, vals):
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height(), fmt_str.format(v),
                        ha="center", va="bottom", fontsize=7.5, color=INK)
    ax.set_xticks(x, groups)
    style_grid(ax, axis="y")


def plot_ambiguity(results):
    M = results["metrics"]["full"]
    buckets = list(M["cnn_hard"]["by_ambiguity"])
    short = [b.replace(" (", "\n(") for b in buckets]
    rows = [("acc_any_top", "Accuracy (any top vote)", "{:.0%}"),
            ("kl", "KL to human votes (lower = better)", "{:.2f}"),
            ("model_confidence", "Average model confidence", "{:.0%}")]
    fig, axes = plt.subplots(3, 2, figsize=(9.5, 9), sharey="row")
    for c, arch in enumerate(ARCHS):
        for r, (key, ylabel, f) in enumerate(rows):
            ax = axes[r, c]
            vals = {lab: [M[f"{arch}_{lab}"]["by_ambiguity"][b][key] for b in buckets] for lab in ["hard", "soft"]}
            if key == "model_confidence":   # human agreement as a reference bar
                vals["human"] = [M["cnn_hard"]["by_ambiguity"][b]["human_top_share"] for b in buckets]
            grouped_bars(ax, short, vals, f)
            if c == 0:
                ax.set_ylabel(ylabel)
            if r == 0:
                ax.set_title(ARCHS[arch], loc="left")
    handles, labels = axes[2, 0].get_legend_handles_labels()
    fig.suptitle("Soft labels track human uncertainty; hard labels stay overconfident on ambiguous faces",
                 x=0.02, ha="left", fontweight="bold", color=INK)
    fig.legend(handles, labels, frameon=False, ncol=3, loc="upper left", bbox_to_anchor=(0.02, 0.975), fontsize=9)
    fig.tight_layout(rect=(0, 0, 1, 0.935))
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "results_by_ambiguity.png")
    plt.close(fig)


def plot_calibration(probs, test, n_bins=10):
    fig, axes = plt.subplots(1, 2, figsize=(9, 4), sharey=True)
    for ax, arch in zip(axes, ARCHS):
        ax.plot([0, 1], [0, 1], linestyle="--", color=INK_2, linewidth=1, label="Perfect calibration")
        for lab in ["hard", "soft"]:
            p = probs[f"{arch}_{lab}"]
            conf, correct = p.max(1), p.argmax(1) == test["hard"]
            bins = np.minimum((conf * n_bins).astype(int), n_bins - 1)
            xs, ys = [], []
            for b in range(n_bins):
                m = bins == b
                if m.sum() >= 20:      # skip nearly empty bins
                    xs.append(conf[m].mean())
                    ys.append(correct[m].mean())
            ax.plot(xs, ys, marker="o", markersize=5, linewidth=2, color=LABEL_COLOR[lab], label=LABEL_NAME[lab])
        ax.set_title(ARCHS[arch], loc="left")
        ax.set_xlabel("Model confidence")
        ax.set_xlim(0.1, 1.0)
        ax.set_ylim(0, 1.0)
        style_grid(ax, axis="both")
    axes[0].set_ylabel("Actual accuracy (majority label)")
    axes[0].legend(frameon=False, loc="upper left", fontsize=8)
    fig.suptitle("Calibration vs majority label: hard = overconfident (below line), soft = underconfident (above)",
                 x=0.02, ha="left", fontweight="bold", color=INK)
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "results_calibration.png")
    plt.close(fig)


def plot_per_class_f1(results):
    M = results["metrics"]["full"]
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.2), sharex=True)
    y = np.arange(len(CLASSES))
    for ax, arch in zip(axes, ARCHS):
        for j, lab in enumerate(["hard", "soft"]):
            vals = [M[f"{arch}_{lab}"]["per_class_f1"][c] for c in CLASSES]
            ax.barh(y + (j - 0.5) * 0.38, vals, height=0.36, color=LABEL_COLOR[lab], label=LABEL_NAME[lab])
        ax.set_yticks(y, CLASSES)
        ax.invert_yaxis()
        ax.set_xlim(0, 1)
        ax.set_xlabel("F1 score")
        ax.set_title(ARCHS[arch], loc="left")
        style_grid(ax)
    axes[1].legend(frameon=False, loc="lower right", fontsize=8)
    fig.suptitle("Per-class F1: contempt and disgust lag far behind", x=0.02, ha="left",
                 fontweight="bold", color=INK)
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "results_per_class_f1.png")
    plt.close(fig)


def plot_confusion(results):
    fig, axes = plt.subplots(2, 2, figsize=(11, 10))
    for ax, run in zip(axes.flat, RUN_NAMES):
        cm = np.array(results["confusion_full"][run], dtype=float)
        cm = cm / cm.sum(axis=1, keepdims=True)
        ax.imshow(cm, cmap="Blues", vmin=0, vmax=1)
        for i in range(len(CLASSES)):
            for j in range(len(CLASSES)):
                ax.text(j, i, f"{cm[i, j]:.0%}" if cm[i, j] >= 0.005 else "", ha="center", va="center",
                        fontsize=7, color="white" if cm[i, j] > 0.55 else INK)
        ax.set_xticks(range(len(CLASSES)), [c[:5] for c in CLASSES], rotation=45)
        ax.set_yticks(range(len(CLASSES)), CLASSES)
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Majority label")
        ax.set_title(RUN_NAMES[run], loc="left")
        for s in ax.spines.values():
            s.set_visible(False)
    fig.suptitle("Confusion matrices (rows sum to 100%)", x=0.02, ha="left", fontweight="bold", color=INK)
    fig.tight_layout()
    fig.savefig(FIGURES_DIR / "results_confusion.png")
    plt.close(fig)


def make_figures(results, probs, test, dup):
    FIGURES_DIR.mkdir(parents=True, exist_ok=True)
    plot_ambiguity(results)
    plot_calibration(probs, test)
    plot_per_class_f1(results)
    plot_confusion(results)
